### ISSUE TITLE
nml.parse() cannot read an echoed nml file from schism

### ISSUE THREAD

**Issue by water-e** [CADWRDeltaModeling/BayDeltaSCHISM#37]
Issue is the array items which have a special form.
```
&SCHOUT
 NC_OUT  =           1,
 IOF_HYDRO       =           1, 16*0, 2*1, 5*0, 2*1, 14*0,
 IOF_WWM = 23*1,           0, 4*1, 12*0,
 IOF_GEN =           0,
 IOF_AGE =           1,
 IOF_SED = 6*1, 5*0, 9*1, 9*0,
 IOF_ECO =           0,
 IOF_ICM_CORE    = 17*0,
 IOF_ICM_SILICA  = 2*0,
```

[param.out.nml.txt](https://github.com/CADWRDeltaModeling/BayDeltaSCHISM/files/12116281/param.out.nml.txt)
[tryit.py.txt](https://github.com/CADWRDeltaModeling/BayDeltaSCHISM/files/12116291/tryit.py.txt)

**Comment by dwr-psandhu** [comment]
closing this issue and pursuing it on schimpy
