### ISSUE TITLE
CRS is wrong in numerous examples

### ISSUE THREAD

**Issue by water-e** [CADWRDeltaModeling/BayDeltaSCHISM#40]
The SCHISM CRS is wrong in at least the nudging and hotstart files.

The correct CRS is EPSG:26910.

No CRS should be set to EPSG:32610. 

Impact isn't huge, but the difficulty of realigning this stuff is high.

**Comment by ZhenlinZhang** [comment]
All EPSG:32610 in the directory has been replaced by 26910.
