### ISSUE TITLE
Turn hotstart_nudging data into a launchable, configurable script that does not have to be moved

### ISSUE THREAD

**Issue by water-e** [CADWRDeltaModeling/BayDeltaSCHISM#61]
Currently it is in bdschism/hotstart_nudging.py and the script has to be copied to be useful. Instead, please add argparse. Call t0 "run_start" and include nudging length in days. The default for repo should be 
//cnrastore-bdo/Modeling_Data/jenkins_repo_staging/continuous/formatted.

That may get renamed eventuall. As I write, some of the downloads are in an odd state.

Ideally, the list of stations that is in the file (including ones designated as "add_upper", which means take the upper sensor, will be the default. The user can add an optional station.csv, with two columns: station_id,subloc. If the subloc is blank it will not go into add_upper.

**Comment by qiangshu** [comment]
hostart_nudging_data has been pushed to schimpy with the required updates.
